services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # painel de management (http://localhost:15672)

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP catch-all (dev)
      - "8025:8025" # web UI para inspecionar os e-mails recebidos
